sudo: false
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4.2"

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - npm test

services:
  - redis-server

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.10"
    - node_js: "0.12"

notifications:
  email:
    - donovan@donovan.bz
